
"use client";
import { useState } from "react";
import { Brand, ComponentExamples, ArrowRight } from "./components";
import tokens from "./tokens.json";

const sections=[["marca","Marca"],["cores","Cores e temas"],["tipografia","Tipografia"],["componentes","Componentes"],["site","Site"]];
const palette=["brand-signature","brand-600","brand-900","ink-900","ink-500","mist-050"] as const;
const semantic=["surface-app","surface-card","surface-sunken","text-primary","text-secondary","text-muted","border-control","action-brand"] as const;

export default function DesignGuide(){
const [theme,setTheme]=useState<"light"|"dark">("light");
return <div className="ds-root" data-ev-theme={theme}><a className="ev-skip" href="#ds-content">Pular para conteúdo</a>
<header className="ds-topbar"><a href="/" aria-label="Eveedence — início"><Brand /></a><div className="ds-topbar-right"><span>Design system · v0.2 proposta</span><div className="ds-theme" role="group" aria-label="Tema da prévia"><button aria-pressed={theme==="light"} onClick={()=>setTheme("light")}>Claro</button><button aria-pressed={theme==="dark"} onClick={()=>setTheme("dark")}>Escuro</button></div><a href="/">Ver o site <ArrowRight size={14} aria-hidden="true" /></a></div></header>
<div className="ds-layout"><aside className="ds-sidebar"><p>Fundamentos e aplicações</p><nav aria-label="Seções do design system">{sections.map(([id,label],i)=><a key={id} href={"#"+id}><span>0{i+1}</span>{label}</a>)}</nav></aside>
<main id="ds-content" className="ds-main"><div className="ds-intro"><div><p className="ev-eyebrow ev-eyebrow--brand">Eveedence · Evidence Operations</p><h1>A mesma marca.<br />Mais evidência.</h1><p>Um sistema para perguntar, reconstruir e mostrar o que sustenta uma conclusão.</p></div><p className="ds-intro-note">Atualização com o logotipo oficial atualizado. Geist, componentes de produto e kit do site compartilham a mesma base. Reconstruído a partir das capturas fornecidas.</p></div>
<section id="marca" className="ds-section"><div className="ds-section-head"><h2>01 · Um logotipo, uma identidade.</h2><p className="ev-eyebrow">Geometria original preservada</p></div><div className="ds-brand-grid"><div className="ds-brand-plate"><p className="ev-eyebrow">Logotipo · original</p><Brand /><p className="ev-caption">607 × 91 · preserve a proporção</p></div><div className="ds-brand-plate ds-brand-plate--dark"><p className="ev-eyebrow">Logotipo · fundo escuro</p><Brand /><p className="ev-eyebrow">Mesmo ativo · sem recoloração</p></div></div><p className="ds-note">O vermelho de identidade é #FF0004. O SVG oficial é usado sem redesenho, tagline ou recoloração. Respiro proposto: ao menos ¼ da altura do ativo em cada lado. A identidade não representa status “verificado”. O símbolo anterior foi retirado das aplicações.</p></section>
<section id="cores" className="ds-section"><div className="ds-section-head"><h2>02 · Vermelho na marca. Clareza na interface.</h2><p className="ev-eyebrow">{theme==="light"?"Tema claro":"Tema escuro · proposta"}</p></div><div className="ds-swatches">{palette.map(key=><div className="ds-swatch" key={key}><div className="ds-swatch-color" style={{background:tokens.primitives[key]}}/><div className="ds-swatch-meta"><span>{key}</span><code>{tokens.primitives[key]}</code></div></div>)}</div><div className="ds-semantic">{semantic.map(key=><div className="ds-token" key={key}><span className="ds-token-color" style={{background:tokens[theme][key]}} aria-hidden="true"/><span>{key}</span><code>{tokens[theme][key]}</code></div>)}</div><p className="ds-note">Marca #FF0004 sobre branco: cerca de 4:1. Use a variante de ação #CE0004 com texto branco; não use o vermelho original em texto pequeno sobre branco. Grafite mantém as ações operacionais discretas. Cores de estado têm nomes, ícones e regras próprias.</p></section>
<section id="tipografia" className="ds-section"><div className="ds-section-head"><h2>03 · A pergunta primeiro.</h2><p className="ev-eyebrow">Geist Sans + Geist Mono</p></div>{[
["t-site-display","Quando alguém pedir para provar.",52,650,false,"52–62 px · mobile 40 px"],
["t-page-title","O que sustenta a conclusão?",27,600,false,"27 px / 1.2 · produto"],
["t-section-title","Um caso, uma pergunta.",17,600,false,"17 px / 1.35 · produto"],
["t-site-lead","O fato, a regra e o que ainda falta.",20,400,false,"20 px / 1.55 · site"],
["t-body","Presença de um registro não estabelece integridade.",14,400,false,"14 px / 1.6 · produto"],
["t-body-sm","Nenhum registro de aprovação localizado.",13,400,false,"13 px / 1.6 · produto"],
["t-caption","Exemplo ilustrativo. Suficiência ainda não avaliada.",12.5,400,false,"12.5 px / 1.6"],
["t-control","Reconstrua um caso real",13,600,false,"13 px · alvo mínimo 44 px"],
["t-site-body","Qual era a versão da política no dia da decisão?",16,400,false,"16 px / 1.6 · site"],
["t-site-eyebrow","INCIDENTE #1842 · 14 FEV 2026 · 09:12 UTC",11,500,true,"11 px / 1.6 · identificadores e metadados"]
].map(([name,text,size,weight,mono,note])=><div className="ds-type-row" key={String(name)}><div>{name}</div><div><p style={{fontSize:Number(size),fontWeight:Number(weight),fontFamily:mono?"var(--ev-font-mono)":"var(--ev-font-sans)"}}>{text}</p><small>{note}</small></div></div>)}<p className="ds-note">O lettering do logotipo é um ativo, não uma fonte para interface. Os títulos serifados do editor original não fazem parte da tipografia da marca.</p><div className="ds-spacing" style={{marginTop:32}}>{[4,8,12,16,24,32,48].map(n=><div key={n}><i style={{height:n}}/>{n} px</div>)}</div><p className="ds-note">Base de 4 px. Raios propostos: controles 10 px, cards 18 px, shells 28 px; badges em pill. Curvas dão proximidade; linhas preservam a estrutura das evidências.</p></section>
<section id="componentes" className="ds-section"><div className="ds-section-head"><h2>04 · Precisão em cada estado.</h2><p className="ev-eyebrow">Produto + site</p></div><ComponentExamples/><p className="ds-note">Integridade verificada descreve uma verificação executada com escopo definido. Não equivale a fato verdadeiro, completude ou suficiência. Timestamp provisório e assinatura não verificável continuam explícitos.</p></section>
<section id="site" className="ds-section"><div className="ds-section-head"><h2>05 · A marca aplicada ao problema.</h2><p className="ev-eyebrow">Home + Teste do Custo da Prova</p></div><div className="ds-preview"><div className="ds-preview-bar"><span>Home · tema claro · exemplos ilustrativos</span><a href="/">Abrir em tamanho real <ArrowRight size={14} aria-hidden="true"/></a></div><iframe src="/" title="Prévia da home Eveedence" loading="lazy"/></div><p className="ds-note">A home demonstra o problema e o método de reconstrução. O teste cria uma ficha com as respostas informadas; não envia dados, não calcula score e não avalia documentos.</p><a className="ev-button ev-button--secondary" style={{marginTop:20}} href="/custo-da-prova">Abrir Teste do Custo da Prova <ArrowRight size={16} aria-hidden="true"/></a></section>
<p className="ds-source-note">Proposta v0.2 · fontes locais · tokens gerados de um único JSON · preview do tema escuro · não implica publicação do site ou aprovação de claims.</p>
</main></div></div>;
}
